brew "tree"
brew "bat"
brew "eza"
brew "neovim"
brew "fd"
brew "fzf"
brew "ripgrep"
brew "tree-sitter-cli"
brew "shellcheck"
brew "gh"
brew "git-crypt"
brew "unar"
brew "zsh-syntax-highlighting"
brew "zsh-autosuggestions"
brew "powerlevel10k"
# base interpreter for the ~/.venvs/* virtualenvs (МастерЛенд pipeline)
brew "python@3.14"
# for npm -g ccstatusline (Claude Code status line)
brew "node"

cask "karabiner-elements"
cask "homerow"
cask "raycast"
cask "obsidian"
cask "ghostty"
cask "keepassxc"
cask "vorssaint"
